export const ADD_TASK = "ADD_TASK";
export const DELETE_ALL_COMPLETED_TASKS = "DELETE_ALL_COMPLETED_TASKS";
export const UPDATE_TASK = "UPDATE_TASK";
export const OPEN_TAB = "OPEN_TAB";
export const DELETE_TASK_BY_ID = "DELETE_TASK_BY_ID";