export const ACTIONS = {
  ADD_ONE: "ADD_ONE",
  UPDATE_ONE: "UPDATE_ONE",
  DELETE_ONE: "DELETE_ONE",
  UPDATE_MANY: "UPDATE_MANY",
};

export const TABS = {
  ALL: "ALL",
  COMPLETED: "COMPLETED",
  ACTIVE: "ACTIVE"
}